# Generated by Django 5.2 on 2025-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ingeniero', 'Ingeniero'), ('secretaria', 'Secretaria'), ('contadora', 'Contadora')], default='ingeniero', max_length=20),
        ),
    ]
